# O application.properties é um arquivo de configuração da aplicação Spring Boot
# Nele você configura propriedades que o Spring Boot utiliza para inicializar e executar a aplicação.

spring.application.name=arquiteturaspring

# habilitando a exibição das queries SQL no console
spring.jpa.show-sql=true

# habilitando a inicialização lazy para para as propriedades do sistema e todos os beans da aplicação
spring.main.lazy-initialization=false
