spring.application.name=arquiteturaspring

# habilitando a exibição das queries SQL no console
spring.jpa.show-sql=true

# habilitando a inicialização lazy para para as propriedades do sistema e todos os beans da aplicação
spring.main.lazy-initialization=false
